### ISSUE TITLE
clean up output

### ISSUE THREAD

**Issue by donaldRwilliams** [LangeJens/CliquePercolation#11]
Please clean up the output from the functions so that it just does not output a list

e.g.,

```
cp.k3 <- cpAlgorithm(W, k = 3, method = "weighted", I = 0.09)
cp.k3

```

returns a list that is not very appealing.

why not first make a print function as in the other issue. But then also add a function to extract whatever the user wants and return it in a nice format

**Comment by LangeJens** [comment]
I added print functions for cpAlgorithm and cpPermuteEntropy. Moreover, I added a summary function for cpAlgorithm in which users can extract detailed information. For cpColoredGraph, cpCommunitySizeDistribution, and cpCommunityGraph, I now return the list objects as invisible. This makes sense, given that plotting is the primary goal of the functions. Overall, the output of all functions in the package is now much cleaner.
