### ISSUE TITLE
data sets

### ISSUE THREAD

**Issue by donaldRwilliams** [LangeJens/CliquePercolation#4]
The package can be improved by including some real data. In my `BGGM` package (https://github.com/donaldRwilliams/BGGM) there are quite a few data sets. I would recommend taking at least one of those to use in your package.

**Comment by LangeJens** [comment]
I added two data sets, one with evaluative reactions about Obama, which allows estimating a weighted, undirected network, and one with interactions of amino-acids (taken from igraphdata), which constitutes an unweighted, undirected network.
