### ISSUE TITLE
only supports qgraph object

### ISSUE THREAD

**Issue by donaldRwilliams** [LangeJens/CliquePercolation#8]
I get the following error when providing a weighted adjacency matrix

```
W (network object) must be a qgraph object.
```

Rather than have the user make a qgraph object, as in the examples, why not just do this in the package for the user ?

**Comment by LangeJens** [comment]
As part of the review process, Alex recommended changes such that users can also specify a matrix as input. The error should no longer occur, if you install the package version directly from GitHub. If the error still occurs, please let me know.

**Comment by donaldRwilliams** [comment]
@LangeJens pretty sure I installed the version from github and had the error.

**Comment by LangeJens** [comment]
@donaldRwilliams I checked the functions again and the error message is commented out in all code. Potentially, you installed a version from GitHub before the respective commit? Anyways, the issue made me realize that allowing a Matrix as input requires more changes in different parts of the package that I will also make. I will close the issue once these changes are on GitHub.
